ARTIST_LIST = [
    # --- уже были ---
    "Boulevard Depo",
    "SALUKI",
    "Хаски",
    "Kai Angel",
    "PHARAOH",
    "FRIENDLY THUG 52 NGG",
    "ROCKET",
    "Mnogoznaal",
    "Toxi$",
    "MAYOT",
    "LILDRUGHILL",
    "ICEGERGERT",
    "Темный Принц",
    # --- лирика / старая школа ---
    "Oxxxymiron",
    "Guf",
    "25/17",
    "Noize MC",
    "K.A.N.T.O.",
    "Смоки Мо",
    "Птаха",
    "Баста",
    "Centr",
    "Карандаш",
    "Rigos",
    # --- новая школа / trap ---
    "FACE",
    "Big Baby Tape",
    "Yanix",
    "ATL",
    "Kizaru",
    "OG Buda",
    "Scally Milano",
    "Slava Marlow",
    "HoodWink",
    "SEEMEE",
    "Drago",
    # --- мелодичный / rnb ---
    "Скриптонит",
    "Gone.Fludd",
    "Thomas Mraz",
    "Markul",
    "Flesh",
    "Lil Morty",
    "ЛСП",
    "Федук",
    # --- экспериментальный / cloud ---
    "OBLADAET",
    "IC3PEAK",
    "Instasamka",
]

ARTIST_DEFAULT_TAGS: dict[str, list[str]] = {
    "Boulevard Depo": ["Cloud Rap", "New School", "Experimental", "Vaporwave", "Abstract"],
    "SALUKI": ["Alternative Hip-Hop", "Trap", "RnB", "Melodic Rap", "Emotional"],
    "Хаски": ["Social Rap", "Industrial", "Abstract", "Lyrical", "Dark"],
    "Kai Angel": ["Rage", "Trap", "Hyperpop", "Aggressive", "Meme Rap"],
    "PHARAOH": ["Cloud Rap", "Emo Rap", "Plugg", "Dark Trap", "Melodic"],
    "FRIENDLY THUG 52 NGG": ["Drill", "Gangsta Rap", "Phonk", "Underground", "Storytelling"],
    "ROCKET": ["Cloud Rap", "Mumble Rap", "Ambient", "Spacey", "Chill"],
    "Mnogoznaal": ["Abstract Hip-Hop", "Horrorcore", "Dark Trap", "Atmospheric", "Deep"],
    "Toxi$": ["Trap", "Plug", "New School", "Energetic", "Youth"],
    "MAYOT": ["Trap", "Mumble Rap", "New School", "Street Rap", "Hard"],
    "LILDRUGHILL": ["Trap", "New School", "RnB", "Melodic Rap"],
    "ICEGERGERT": ["New School", "Melodic Rap", "Pop Trap", "Mainstream"],
    "Темный Принц": ["Trap", "New School", "Dark", "Minimalism"],
    "Oxxxymiron": ["Lyrical", "Abstract", "Old School", "Conceptual", "Complex"],
    "Guf": ["Lyrical", "Old School", "Alternative Hip-Hop", "Street Rap"],
    "25/17": ["Hardcore Hip-Hop", "Social Rap", "Lyrical", "Street Rap", "Aggressive"],
    "Noize MC": ["Alternative Hip-Hop", "Political", "Lyrical", "Experimental"],
    "K.A.N.T.O.": ["Lyrical", "Abstract", "Alternative Hip-Hop", "Storytelling"],
    "Смоки Мо": ["Old School", "Lyrical", "Street Rap", "Storytelling"],
    "Птаха": ["Old School", "Lyrical", "Street Rap", "Gangsta Rap"],
    "Баста": ["Alternative Hip-Hop", "Melodic", "Lyrical", "Mainstream"],
    "Centr": ["Old School", "Street Rap", "Lyrical", "Storytelling"],
    "Карандаш": ["Old School", "Underground", "Lyrical", "Abstract"],
    "Rigos": ["Lyrical", "Old School", "Alternative Hip-Hop"],
    "FACE": ["Mumble Rap", "Trap", "Shock Rap", "New School", "Aggressive"],
    "Big Baby Tape": ["Trap", "Plug", "New School", "Energetic"],
    "Yanix": ["Cloud Rap", "Trap", "Melodic", "New School"],
    "ATL": ["Trap", "Street Rap", "New School", "Aggressive"],
    "Kizaru": ["Cloud Rap", "Trap", "Mumble Rap", "New School", "Chill"],
    "OG Buda": ["Trap", "Plug", "Aggressive", "New School"],
    "Scally Milano": ["Trap", "New School", "Street Rap"],
    "Slava Marlow": ["Trap", "New School", "Melodic", "Mainstream"],
    "HoodWink": ["Drill", "Trap", "Aggressive", "Underground"],
    "SEEMEE": ["Trap", "New School", "Underground"],
    "Drago": ["Trap", "New School", "Melodic"],
    "Скриптонит": ["Trap", "RnB", "Melodic", "New School", "Smooth"],
    "Gone.Fludd": ["Cloud Rap", "RnB", "Melodic", "New School", "Smooth"],
    "Thomas Mraz": ["RnB", "Melodic Rap", "Pop Trap", "New School"],
    "Markul": ["Emo Rap", "Dark Trap", "Melodic", "New School"],
    "Flesh": ["Cloud Rap", "Emo Rap", "Dark", "Melodic"],
    "Lil Morty": ["Emo Rap", "Melodic", "Dark", "New School"],
    "ЛСП": ["Pop Rap", "Melodic", "New School", "Mainstream"],
    "Федук": ["Pop Rap", "RnB", "Melodic", "Mainstream"],
    "OBLADAET": ["Cloud Rap", "Experimental", "Abstract", "New School"],
    "IC3PEAK": ["Experimental", "Electronic", "Dark", "Alternative"],
    "Instasamka": ["Trap", "Hyperpop", "Aggressive", "New School"],
}

ALBUM_TAGS: dict[str, dict[str, list[str]]] = {
    "Boulevard Depo": {
        "RAPP": ["Cloud Rap", "Atmospheric", "Dark", "Eerie"],
        "Old Blood": ["Experimental", "Vaporwave", "Cloud Rap", "Abstract", "Eerie"],
        "RAPP2": ["Cloud Rap", "New School", "Melodic", "Aggressive"],
        "QUAYLE": ["Eerie", "Minimalism", "Experimental", "Abstract"],
        "ФУТУРОАРХАИКА": ["Dark", "Cloud Rap", "Lyrical"],
    },
    "SALUKI": {
        "Властелин Калек (Lord of the Cripples)": ["Alternative Hip-Hop", "Emotional", "Conceptual", "Dark", "Storytelling"],
        "НАШИХ ГЛАЗ ФУНДАМЕНТ": ["Trap", "Melodic", "RnB", "Pop Trap", "Chill"],
        "УЛИЦА ПОДЪЕЗД ДОМ": ["Trap", "New School", "Mumble Rap"],
    },
    "Хаски": {
        "Хошхоног": ["Dark", "Industrial", "Drones", "Hardcore Hip-Hop"],
        "Любимые песни (воображаемых) людей": ["Social Rap", "Lyrical", "Philosophical", "Abstract", "Conceptual"],
        "Локид": ["Alternative Hip-Hop", "Experimental", "Abstract"],
    },
    "Kai Angel": {
        "Heavy Metal": ["Rage", "Hyperpop", "Aggressive", "Meme Rap", "Experimental"],
        "BABY MELON": ["Rage", "Hyperpop", "Energetic"],
    },
    "PHARAOH": {
        "Million Dollar Depression": ["Emo Rap", "Melodic", "Dark Trap", "Goth"],
        "Правило": ["Cloud Rap", "Vaporwave", "Spacey", "Ambient"],
        "REDЯUM": ["Dark Trap", "Aggressive", "New School"],
    },
    "FRIENDLY THUG 52 NGG": {
        "Cruiser Aurora": ["Drill", "Gangsta Rap", "Phonk", "Underground", "Storytelling", "Dark"],
        "Montenegro": ["Drill", "Underground", "Street Rap"],
    },
    "ROCKET": {
        "Swag Season": ["Cloud Rap", "Mumble Rap", "Ambient", "Spacey", "Chill"],
        "Ego Trippin'": ["Dark Trap", "Aggressive", "Cloud Rap"],
    },
    "Mnogoznaal": {
        "Горе (Woe)": ["Abstract Hip-Hop", "Conceptual", "Horrorcore", "Atmospheric", "Dark"],
        "КРУГ (Circle)": ["Experimental", "Industrial", "Storytelling", "Abstract"],
    },
    "Toxi$": {
        "HOTSPOT": ["Trap", "Plug", "New School", "Energetic", "Youth"],
        "JAZZ DOLLS": ["Plug", "Ambient", "New School"],
    },
    "MAYOT": {
        "Ghetto Garden": ["Trap", "New School", "Street Rap", "Hard", "Mumble Rap"],
        "ЗАПРАВКА (ZAPRAVKA)": ["Trap", "Hard", "Street Rap"],
    },
    "LILDRUGHILL": {
        "All the songs are about money": ["Trap", "New School", "RnB", "Melodic Rap"],
        "DRUGG": ["Melodic Rap", "Pop Trap", "RnB"],
    },
    "Oxxxymiron": {
        "Горгород": ["Conceptual", "Storytelling", "Lyrical", "Abstract", "Dark"],
        "Мирмиллон": ["Old School", "Lyrical", "Abstract", "Complex"],
        "Вечный жид": ["Old School", "Lyrical", "Abstract", "Dark"],
    },
    "Скриптонит": {
        "Уроборос": ["Trap", "RnB", "Melodic", "Smooth", "Conceptual"],
        "Дом с нормальными явлениями": ["Trap", "Melodic", "RnB", "Chill"],
    },
    "FACE": {
        "Individuum": ["Trap", "Shock Rap", "Experimental", "Aggressive"],
        "Пространство": ["Trap", "New School", "Aggressive"],
    },
    "Markul": {
        "Там, где нас нет": ["Emo Rap", "Dark Trap", "Melodic", "Atmospheric"],
        "Серый": ["Emo Rap", "Dark", "Melodic", "New School"],
    },
    "25/17": {
        "Русский подорожник": ["Hardcore Hip-Hop", "Social Rap", "Lyrical", "Dark"],
        "Евангелие от пацана": ["Street Rap", "Lyrical", "Storytelling", "Aggressive"],
    },
    "Баста": {
        "Баста 3": ["Alternative Hip-Hop", "Lyrical", "Melodic", "Mainstream"],
        "Аcousтика": ["Alternative Hip-Hop", "Lyrical", "Melodic", "Emotional"],
    },
    "Gone.Fludd": {
        "HOTLOVE": ["Cloud Rap", "RnB", "Melodic", "Smooth"],
        "Спасибо": ["Cloud Rap", "Melodic", "Emotional", "RnB"],
    },
    "Kizaru": {
        "Kizaru": ["Cloud Rap", "Trap", "Mumble Rap", "Chill"],
        "11:11": ["Cloud Rap", "Melodic", "Chill", "Ambient"],
    },
    "IC3PEAK": {
        "Сладкий сон": ["Experimental", "Dark", "Electronic", "Alternative"],
        "Трэш панда": ["Experimental", "Dark", "Electronic", "Aggressive"],
    },
}
